name: app_env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - flask=2.1.3
  - nltk=3.7
  - numpy=1.22.3
  - pandas=1.4.3
  - python=3.9.1
  - scikit-learn=1.0.2
  - tensorflow=2.7.0
  - keras=2.7.0
